/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazEditorTexto;

import com.sun.glass.events.KeyEvent;
import gramaticaCLRS.AnalizadorLexico;
import gramaticaCLRS.SintaxCLRS;
import gramaticaLNZ.AnalizadorLexico2;
import gramaticaLNZ.SintaxLNZ;
import gramaticaPNT.AnalizadorLexico3;
import gramaticaPNT.SintaxPNT;
import gramaticaTMP.AnalizadorLexico4;
import gramaticaTMP.SintaxTMP;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luisitopapurey
 */
public class PanelTexto extends javax.swing.JPanel {

    private String path, texto;
    private String[] textos;

    /**
     * Creates new form PanelTexto
     *
     * @param texto
     */       
     
    public PanelTexto(String[] texto, String path) throws Exception {
        initComponents();
        this.path = path;
        this.textos = texto;
        System.out.println("hola mundo");
        if(path.endsWith(".clrs")){
            txtArea.setText(InterfazTexto.textos[1]);
        } else if(path.endsWith(".lnz")){
            txtArea.setText(InterfazTexto.textos[0]);
        } else if(path.endsWith(".tmp")){
            txtArea.setText(InterfazTexto.textos[2]);
        } else if(path.endsWith(".pnt")){
            txtArea.setText(InterfazTexto.textos[3]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAreaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyPressed
        if(evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_S){
            if(path.endsWith(".clrs")){
                InterfazTexto.textos[1] = txtArea.getText();
            } else if(path.endsWith(".lnz")){
                InterfazTexto.textos[0] = txtArea.getText();
            } else if(path.endsWith(".tmp")){
                InterfazTexto.textos[2] = txtArea.getText();
            } else if(path.endsWith(".pnt")){
                InterfazTexto.textos[3] = txtArea.getText();
            }   
          
        }
    }//GEN-LAST:event_txtAreaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
