
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 09 16:59:34 CST 2020
//----------------------------------------------------

package gramaticaLNZ;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dimension_y = 17;
  public static final int nombre = 8;
  public static final int dimension_x = 16;
  public static final int tipo = 9;
  public static final int codigoHex = 23;
  public static final int png = 18;
  public static final int PALABRA = 24;
  public static final int Fondo = 10;
  public static final int Blue = 14;
  public static final int ID = 22;
  public static final int COMILLAS = 7;
  public static final int HEX = 20;
  public static final int DOS_PUNTOS = 6;
  public static final int LIENZOS = 3;
  public static final int cuadro = 15;
  public static final int COMA = 2;
  public static final int gif = 19;
  public static final int EOF = 0;
  public static final int size = 11;
  public static final int Red = 12;
  public static final int Green = 13;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int LLAVE_B = 5;
  public static final int LLAVE_A = 4;
}

