
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 14 22:27:18 CST 2020
//----------------------------------------------------

package gramaticaPNT;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AGRUPACION_A = 18;
  public static final int NUMERO = 36;
  public static final int DIFERENCIA = 13;
  public static final int POR = 22;
  public static final int VARS = 25;
  public static final int RANGO = 6;
  public static final int INT = 26;
  public static final int LLAVE_B = 15;
  public static final int LLAVE_A = 14;
  public static final int INSTRUCCIONES = 31;
  public static final int AND = 38;
  public static final int IGUAL = 8;
  public static final int OR = 39;
  public static final int DIV = 40;
  public static final int IF = 33;
  public static final int ID = 37;
  public static final int PUNTO_COMA = 4;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int COMENTARIO_A = 3;
  public static final int COMILLAS = 5;
  public static final int TRUE = 29;
  public static final int error = 1;
  public static final int PINTAR = 32;
  public static final int COMA = 2;
  public static final int MENOS = 21;
  public static final int MENOR = 9;
  public static final int MAYOR = 10;
  public static final int DOBLE_IGUAL = 7;
  public static final int ELSE = 34;
  public static final int WHILE = 35;
  public static final int PARENTESIS_B = 17;
  public static final int PARENTESIS_A = 16;
  public static final int MAYOR_IGUAL = 12;
  public static final int STRING = 27;
  public static final int COMENTARIO_B_B = 24;
  public static final int COMENTARIO_B_A = 23;
  public static final int MENOR_IGUAL = 11;
  public static final int FALSE = 30;
  public static final int MAS = 20;
  public static final int AGRUPACION_B = 19;
}

