
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 21 22:53:11 CST 2020
//----------------------------------------------------

package gramaticaTMP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AGRUPACION_A = 5;
  public static final int TIEMPOS = 9;
  public static final int COMA = 2;
  public static final int id = 13;
  public static final int inicio = 10;
  public static final int imagenes = 12;
  public static final int EOF = 0;
  public static final int LLAVE_B = 16;
  public static final int LLAVE_A = 15;
  public static final int NUMERO = 8;
  public static final int COMILLAS = 4;
  public static final int ID = 7;
  public static final int error = 1;
  public static final int duracion = 14;
  public static final int DOS_PUNTOS = 3;
  public static final int fin = 11;
  public static final int AGRUPACION_B = 6;
}

