
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 08 23:12:47 CST 2020
//----------------------------------------------------

package gramaticaCLRS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 13;
  public static final int Green = 3;
  public static final int Blue = 5;
  public static final int Red = 4;
  public static final int EOF = 0;
  public static final int COLORES = 2;
  public static final int LLAVE_B = 8;
  public static final int NUMERO = 10;
  public static final int LLAVE_A = 7;
  public static final int ID = 11;
  public static final int error = 1;
  public static final int codigoHex = 12;
  public static final int DOS_PUNTOS = 9;
  public static final int HEX = 6;
}

