/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazEditorGrafico;

import OperacionEditorGrafico.LlenadoPaneles;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pollitos.Colores;
import pollitos.LienzoColor;

/**
 *
 * @author luisGonzalez
 */
public class NuevoColor extends javax.swing.JDialog {

    private LienzoColor nuevoColor = null;
    private Colores misColores;
    private JLabel lblSeleccionado;
    private LlenadoPaneles paneles;
    
    /**
     * Creates new form NuevoColor
     */
    public NuevoColor(java.awt.Frame parent, boolean modal, Colores misColores, JLabel lblSeleccionado, LlenadoPaneles paneles) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.misColores = misColores;
        this.lblSeleccionado = lblSeleccionado;
        this.paneles = paneles;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnColor = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnColor.setText("Elige un color");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColor)
                    .addComponent(btnConfirmar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debes confirmar el parametro de nombre.");
        } else if(nuevoColor == null){
            JOptionPane.showMessageDialog(null, "No has elegido un color aun");
        } else {
            nuevoColor.setIdColor(txtNombre.getText());
            misColores.getListColores().add(nuevoColor);
            paneles.asignacionColores(misColores, lblSeleccionado);
            paneles.asignacionNombresColores(misColores);
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        Color color = JColorChooser.showDialog(this, "Elige un color", this.getBackground());
        nuevoColor = new LienzoColor();
        nuevoColor.setAzul(color.getBlue());
        nuevoColor.setRojo(color.getRed());
        nuevoColor.setVerde(color.getGreen());
        
    }//GEN-LAST:event_btnColorActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
