/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazEditorGrafico;

import OperacionEditorGrafico.LlenadoPaneles;
import OperacionEditorGrafico.PanelMatriz;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import pollitos.Colores;
import pollitos.Lienzos;
import pollitos.Tiempos;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 * @author luisGonzalez
 */
public class PanelGrafico extends javax.swing.JPanel {

    private Lienzos miLienzo;
    private Tiempos misTiempos;
    private Colores misColores;
    private final LlenadoPaneles paneles;
    private final PanelMatriz principal;
    public JLabel[][] tableroColor;
    public JLabel[][] tableroNombreColor;
    public JLabel[][] tableroPrincipal;
    public static String color;

    /**
     * Creates new form PanelGrafico
     */
    public PanelGrafico(Lienzos miLienzo, Tiempos misTiempos, Colores misColores) {
        initComponents();
        this.miLienzo = miLienzo;
        this.misTiempos = misTiempos;
        this.misColores = misColores;
        lblSeleccionado.setBorder(new LineBorder(Color.black));
        paneles = new LlenadoPaneles(panelColores, tableroColor, tableroNombreColor, panelNombres);
        principal = new PanelMatriz(panelMatriz, tableroPrincipal);
        paneles.llenadoPanel1(misTiempos, txtCantidad, txtInicio, txtFin);
        paneles.llenadoPanel2(misTiempos, comboImg);
        
        paneles.asignacionColores(misColores, lblSeleccionado);
        paneles.asignacionNombresColores(misColores);
        principal.crearTablero(miLienzo, borrador);
     /*   panelColores.setLayout(new GridLayout(misColores.getListColores().size(), 1));
        for (int i = 0; i < misColores.getListColores().size(); i++) {
            for (int j = 0; j < 1; j++) {
                panelColores.add(tableroColor[i][j]);
                panelColores.validate();
                panelColores.repaint();
            }
        }*/
     
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelArea1 = new javax.swing.JPanel();
        panelLNZ = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtInicio = new javax.swing.JTextField();
        txtFin = new javax.swing.JTextField();
        panelCLRS = new javax.swing.JPanel();
        panelColores = new javax.swing.JLabel();
        panelNombres = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSeleccionado = new javax.swing.JLabel();
        borrador = new javax.swing.JCheckBox();
        panelLNZ1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboImg = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        panelMatriz = new javax.swing.JLabel();

        jLabel1.setText("Cantidad");

        jLabel2.setText("Inicio");

        jLabel3.setText("Fin");

        javax.swing.GroupLayout panelLNZLayout = new javax.swing.GroupLayout(panelLNZ);
        panelLNZ.setLayout(panelLNZLayout);
        panelLNZLayout.setHorizontalGroup(
            panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLNZLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(txtInicio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFin))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelLNZLayout.setVerticalGroup(
            panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLNZLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelLNZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel6.setText("Color seleccionado:");

        borrador.setText("Borrador activo");

        javax.swing.GroupLayout panelCLRSLayout = new javax.swing.GroupLayout(panelCLRS);
        panelCLRS.setLayout(panelCLRSLayout);
        panelCLRSLayout.setHorizontalGroup(
            panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLRSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCLRSLayout.createSequentialGroup()
                        .addComponent(borrador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCLRSLayout.createSequentialGroup()
                        .addGroup(panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(lblSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        panelCLRSLayout.setVerticalGroup(
            panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCLRSLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelCLRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Imagen");

        comboImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboImgActionPerformed(evt);
            }
        });

        jLabel5.setText("Duracion:");

        javax.swing.GroupLayout panelLNZ1Layout = new javax.swing.GroupLayout(panelLNZ1);
        panelLNZ1.setLayout(panelLNZ1Layout);
        panelLNZ1Layout.setHorizontalGroup(
            panelLNZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLNZ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLNZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboImg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLNZ1Layout.createSequentialGroup()
                        .addGroup(panelLNZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLNZ1Layout.setVerticalGroup(
            panelLNZ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLNZ1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelArea1Layout = new javax.swing.GroupLayout(panelArea1);
        panelArea1.setLayout(panelArea1Layout);
        panelArea1Layout.setHorizontalGroup(
            panelArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArea1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCLRS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelArea1Layout.createSequentialGroup()
                        .addComponent(panelLNZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelLNZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelArea1Layout.setVerticalGroup(
            panelArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArea1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLNZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLNZ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelCLRS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboImgActionPerformed
        paneles.cambioDuracion(misTiempos, comboImg.getSelectedItem().toString(), txtDuracion);
    }//GEN-LAST:event_comboImgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox borrador;
    private javax.swing.JComboBox<String> comboImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSeleccionado;
    private javax.swing.JPanel panelArea1;
    private javax.swing.JPanel panelCLRS;
    private javax.swing.JLabel panelColores;
    private javax.swing.JPanel panelLNZ;
    private javax.swing.JPanel panelLNZ1;
    private javax.swing.JLabel panelMatriz;
    private javax.swing.JLabel panelNombres;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtInicio;
    // End of variables declaration//GEN-END:variables
}
